easy_admin:
    site_name: 'Chubbycoon'
    design:
        brand_color: '#205081'
        color_scheme: 'dark'
        form_theme: 'form/fields_easyadmin.html.twig'
        assets:
            css:
                - 'build/css/admin.css'
            js:
                - 'build/js/admin.js'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H\hi'
    list:
        actions:
            - { name: 'search', label: 'Rechercher', 'icon': 'search' }
            - { name: 'new', label: 'Créer', 'icon': 'plus' }
            - { name: 'edit', label: 'Éditer', 'icon': 'pencil' }
            - { name: 'delete', label: 'Supprimer', 'icon': 'trash-o' }
